#
# Docker Compose for the Resume Analyzer Backend
#
# Author: Wagner Pinheiro
# Date: 2024-07-12
#
# This file defines the services, networks, and volumes for the backend application.
# It sets up the FastAPI/Uvicorn service and a separate ChromaDB service for vector storage.
#

version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - CHROMA_HOST=chromadb
    depends_on:
      - chromadb
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  chromadb:
    image: chromadb/chroma
    ports:
      - "8080:8000" # Exposing ChromaDB on host port 8080 to avoid conflict with our API on 8000
    volumes:
      - chroma_data:/chroma/.chroma/index

volumes:
  chroma_data:
